# Generated by Django 5.0.4 on 2024-08-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="listed_at",
        ),
        migrations.RemoveField(
            model_name="item",
            name="sold_at",
        ),
    ]
