# Generated by Django 5.0.4 on 2024-07-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_categories_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='listed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
