# Generated by Django 5.0.4 on 2024-09-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_alter_itemimages_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("listed", "Listed"),
                    ("recalled", "Recalled"),
                    ("sold", "Sold"),
                    ("abandoned", "Abandoned"),
                ],
                default="available",
                max_length=255,
            ),
        ),
    ]
