# Generated by Django 5.0.4 on 2024-09-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='memberprofile',
            table='member_profiles',
        ),
    ]
