# Generated by Django 5.0.4 on 2024-07-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_new_listing_notifications_membernotificationpreferences_email_notifications_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberPaymentDetails',
        ),
    ]
