version: '3.8'

services:
  web:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - DB_HOST=${HOST}
      - DB_PORT=${PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "
      while ! pg_isready -h db -p 5432 -q; do
        echo 'Waiting for PostgreSQL to be ready...';
        sleep 2;
      done;
      echo 'PostgreSQL is ready.';
      python manage.py collectstatic --noinput;
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py sync_categories_conditions;
      python manage.py runserver 0.0.0.0:8000;
      "
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
