version: '3.8'

services:
  web:
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: >
      sh -c "
      while ! pg_isready -h db -p 5432 -q; do
        echo 'Waiting for PostgreSQL to be ready...';
        sleep 2;
      done;
      echo 'PostgreSQL is ready.';
      python manage.py collectstatic --noinput;
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py sync_categories_conditions;
      python manage.py sync_recall_reasons;
      python manage.py sync_payment_providers;
      python manage.py sync_store_supplies;
      python manage.py runserver 0.0.0.0:8000;
      "
  
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery_worker:
    command: celery -A async_tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    command: celery -A async_tasks.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
