version: '3.8'

services:
  web:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - DB_HOST=${HOST}
      - DB_PORT=${PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: >
      sh -c "
      while ! pg_isready -h db -p 5432 -q; do
        echo 'Waiting for PostgreSQL to be ready...';
        sleep 2;
      done;
      echo 'PostgreSQL is ready.';
      python manage.py collectstatic --noinput;
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py sync_categories_conditions;
      python manage.py sync_recall_reasons;
      python manage.py sync_payment_providers;
      python manage.py sync_store_supplies;
      python manage.py runserver 0.0.0.0:8000;
      "
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      target: development
    command: celery -A async_tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}         
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    build:
      context: .
      target: development
    command: celery -A async_tasks.celery beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}         
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
