version: '3.8'

services:
  web:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:123456@db:5432/tagandtake_core
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "
      while ! pg_isready -h db -p 5432 -q; do
        echo 'Waiting for PostgreSQL to be ready...';
        sleep 2;
      done;
      echo 'PostgreSQL is ready.';
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py runserver 0.0.0.0:8000;
      "
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tagandtake_core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
