# Generated by Django 5.0.4 on 2024-07-30 11:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('stores', '0002_remove_tag_status_remove_taggroup_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ISSUE', 'Issue'), ('STORE DISCRESSION', 'Store Discretion'), ('OWNER REQUEST', 'Owner Request')], max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recall_reasons',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroe_comission', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_listing_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.tag')),
            ],
            options={
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='RecalledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_listing_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeprofile')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.recallreason')),
            ],
            options={
                'db_table': 'recalled_item',
            },
        ),
    ]
