# Generated by Django 5.0.4 on 2024-08-19 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("marketplace", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="delistedlisting",
            name="tag",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stores.tag"),
        ),
        migrations.AddField(
            model_name="listing",
            name="item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="items.item"),
        ),
        migrations.AddField(
            model_name="listing",
            name="tag",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stores.tag"),
        ),
        migrations.AddField(
            model_name="recalledlisting",
            name="item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="items.item"),
        ),
        migrations.AddField(
            model_name="recalledlisting",
            name="tag",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stores.tag"),
        ),
        migrations.AddField(
            model_name="recalledlisting",
            name="reason",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.recallreason",
            ),
        ),
        migrations.AddField(
            model_name="delistedlisting",
            name="reason",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.recallreason",
            ),
        ),
        migrations.AddField(
            model_name="soldlisting",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="soldlisting",
            name="item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="items.item"),
        ),
        migrations.AddField(
            model_name="soldlisting",
            name="tag",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stores.tag"),
        ),
    ]
