# Generated by Django 5.0.4 on 2024-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recallreason",
            name="type",
            field=models.CharField(
                choices=[
                    ("issue", "Issue"),
                    ("store discretion", "Store Discretion"),
                    ("owner request", "Owner Request"),
                ],
                max_length=255,
            ),
        ),
    ]
