# Generated by Django 5.0.4 on 2024-09-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delisteditemlisting',
            table='delisted_item_listings',
        ),
        migrations.AlterModelTable(
            name='itemlisting',
            table='item_listings',
        ),
        migrations.AlterModelTable(
            name='recalleditemlisting',
            table='recalled_item_listings',
        ),
        migrations.AlterModelTable(
            name='solditemlisting',
            table='sold_item_listings',
        ),
    ]
