# Generated by Django 5.0.4 on 2024-08-01 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recalledlisting",
            name="original_listing",
        ),
    ]
