# Generated by Django 5.0.4 on 2024-09-15 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solditemlisting",
            name="transaction",
            field=models.OneToOneField(
                default=111,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sold_item_listing",
                to="payments.itempaymenttransaction",
            ),
            preserve_default=False,
        ),
    ]
