# Generated by Django 5.0.4 on 2024-08-09 10:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_remove_recalledlisting_original_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="recalledlisting",
            name="fee_charged_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recalledlisting",
            name="last_fee_charge_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="recalledlisting",
            name="last_fee_charge_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
