# Generated by Django 5.0.4 on 2024-09-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_solditemlisting_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recalleditemlisting",
            name="fee_charged_count",
        ),
        migrations.RemoveField(
            model_name="recalleditemlisting",
            name="last_fee_charge_amount",
        ),
        migrations.RemoveField(
            model_name="recalleditemlisting",
            name="last_fee_charge_at",
        ),
    ]
