# Generated by Django 5.0.4 on 2024-08-09 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_recalledlisting_fee_charged_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recalledlisting",
            name="next_fee_charge_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
