# Generated by Django 5.0.4 on 2024-08-13 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_recalledlisting_next_fee_charge_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delistedlisting",
            name="reason",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.recallreason",
            ),
        ),
    ]
