# Generated by Django 5.0.4 on 2024-09-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("stripe_price_id", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Store Supply",
                "verbose_name_plural": "Store Supplies",
                "db_table": "store_supplies",
            },
        ),
        migrations.CreateModel(
            name="SupplyOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_order",
                        to="payments.supplypaymenttransaction",
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tagandtake.storesupply",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply Order Item",
                "verbose_name_plural": "Supply Order Items",
                "db_table": "supply_order_items",
            },
        ),
    ]
