# Generated by Django 5.0.4 on 2024-09-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreSupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("stripe_price_id", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Store Supply",
                "verbose_name_plural": "Store Supplies",
                "db_table": "store_supplies",
            },
        ),
    ]
