# Generated by Django 5.0.4 on 2024-09-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tagandtake", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storesupply",
            name="available_quantity",
        ),
    ]
