# Generated by Django 5.0.4 on 2024-09-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagandtake', '0002_remove_storesupply_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesupply',
            name='price',
        ),
    ]
