# Generated by Django 5.0.4 on 2024-09-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagandtake', '0003_remove_storesupply_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesupply',
            options={'verbose_name': 'Store Supply', 'verbose_name_plural': 'Store Supplies'},
        ),
        migrations.AlterModelTable(
            name='storesupply',
            table='store_supplies',
        ),
    ]
