# Generated by Django 5.0.4 on 2024-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="payout",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payout",
                "verbose_name_plural": "Payouts",
            },
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterModelTable(
            name="paymenttransaction",
            table="payment_transactions",
        ),
        migrations.AlterModelTable(
            name="payout",
            table="payouts",
        ),
    ]
