# Generated by Django 5.0.4 on 2024-09-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pendingmembertransfer",
            old_name="balance",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="pendingmembertransfer",
            name="latest_charge",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pendingmembertransfer",
            name="payment_intent_id",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
