# Generated by Django 5.0.4 on 2024-08-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberpaymentdetails",
            name="stripe_account_id",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="memberpaymentdetails",
            name="stripe_customer_id",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="storepaymentdetails",
            name="stripe_account_id",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="storepaymentdetails",
            name="stripe_customer_id",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
