# Generated by Django 5.0.4 on 2024-09-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempaymenttransaction",
            name="latest_charge",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
