# Generated by Django 5.0.4 on 2024-09-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("payments", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberfailedpayout",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="failed_payouts",
                to="members.memberprofile",
            ),
        ),
        migrations.AlterField(
            model_name="storefailedpayout",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="failed_payouts",
                to="stores.storeprofile",
            ),
        ),
    ]
