# Generated by Django 5.0.4 on 2024-09-13 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("payments", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberPaymentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_account_id", models.CharField(max_length=255)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_account",
                        to="members.memberprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Payment Account",
                "verbose_name_plural": "Member Payment Accounts",
                "db_table": "member_payment_accounts",
            },
        ),
        migrations.CreateModel(
            name="MemberPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "stripe_payout_reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="members.memberprofile",
                    ),
                ),
                (
                    "payout_provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_payouts",
                        to="payments.payoutprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Payout",
                "verbose_name_plural": "Member Payouts",
                "db_table": "member_payouts",
            },
        ),
        migrations.CreateModel(
            name="MemberFailedPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_payouts",
                        to="members.memberprofile",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_member_payout",
                        to="payments.memberpayout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Failed Payout",
                "verbose_name_plural": "Member Failed Payouts",
                "db_table": "failed_member_payouts",
            },
        ),
        migrations.CreateModel(
            name="MemberWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="members.memberprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Wallet",
                "verbose_name_plural": "Member Wallets",
                "db_table": "member_wallets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StorePaymentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_account_id", models.CharField(max_length=255)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_account",
                        to="stores.storeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Payment Account",
                "verbose_name_plural": "Store Payment Accounts",
                "db_table": "store_payment_accounts",
            },
        ),
        migrations.CreateModel(
            name="StorePayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "stripe_payout_reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payout_provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_payouts",
                        to="payments.payoutprovider",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="stores.storeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Payout",
                "verbose_name_plural": "Store Payouts",
                "db_table": "store_payouts",
            },
        ),
        migrations.CreateModel(
            name="StoreFailedPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_payouts",
                        to="stores.storeprofile",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_store_payout",
                        to="payments.storepayout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Failed Payout",
                "verbose_name_plural": "Store Failed Payouts",
                "db_table": "failed_store_payouts",
            },
        ),
        migrations.CreateModel(
            name="StoreWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="stores.storeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Wallet",
                "verbose_name_plural": "Store Wallets",
                "db_table": "store_wallets",
                "ordering": ["-created_at"],
            },
        ),
    ]
