# Generated by Django 5.0.4 on 2024-09-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_storewallet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memberpaymentaccount",
            old_name="account_id",
            new_name="stripe_account_id",
        ),
        migrations.RenameField(
            model_name="memberpaymentaccount",
            old_name="customer_id",
            new_name="stripe_customer_id",
        ),
        migrations.RenameField(
            model_name="storepaymentaccount",
            old_name="account_id",
            new_name="stripe_account_id",
        ),
        migrations.RenameField(
            model_name="storepaymentaccount",
            old_name="customer_id",
            new_name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="memberpaymentaccount",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="storepaymentaccount",
            name="provider",
        ),
    ]
