# Generated by Django 5.0.4 on 2024-10-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_itempaymenttransaction_latest_charge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faileditempaymenttransaction",
            name="payment_transaction",
        ),
        migrations.RemoveField(
            model_name="failedsuppliespaymenttransaction",
            name="payment_transaction",
        ),
    ]
