# Generated by Django 5.0.4 on 2024-10-01 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
        (
            "payments",
            "0003_remove_faileditempaymenttransaction_payment_transaction_and_more",
        ),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faileditempaymenttransaction",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="failed_item_transactions",
                to="items.item",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faileditempaymenttransaction",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="failed_item_transactions",
                to="stores.storeprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="failedsuppliespaymenttransaction",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="failed_supply_transactions",
                to="stores.storeprofile",
            ),
            preserve_default=False,
        ),
    ]
