# Generated by Django 5.0.4 on 2024-10-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_faileditempaymenttransaction_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faileditempaymenttransaction",
            name="payment_intent_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="failedsuppliespaymenttransaction",
            name="payment_intent_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="faileditempaymenttransaction",
            table="failed_item_transactions",
        ),
    ]
