# Generated by Django 5.0.4 on 2024-09-29 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
        ("supplies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplyorderitem",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_supply_order",
                to="stores.storeprofile",
            ),
            preserve_default=False,
        ),
    ]
