# Generated by Django 5.0.4 on 2024-07-31 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeprofile",
            name="active_tags_count",
        ),
    ]
