# Generated by Django 5.0.4 on 2024-07-28 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="status",
        ),
        migrations.RemoveField(
            model_name="taggroup",
            name="activated",
        ),
    ]
