# Generated by Django 5.0.4 on 2024-06-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='stock_limit',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
