# Generated by Django 5.0.4 on 2024-08-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storeopeninghours',
            table='store_opening_hours',
        ),
    ]
