# Generated by Django 5.0.4 on 2024-08-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_alter_storeopeninghours_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="hash",
        ),
    ]
