# Generated by Django 5.0.4 on 2024-07-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_alter_storeprofile_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeprofile",
            name="profile_photo_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
