# Generated by Django 5.0.4 on 2024-07-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_storeprofile_profile_photo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorePaymentDetails',
        ),
    ]
