version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production  # PRODUCTION TARGET
    env_file:
      - docker/envs/.env.staging  # STAGING ENV

  db:
    env_file:
      - docker/envs/.env.staging  # STAGING ENV

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production  # PRODUCTION TARGET
    env_file:
      - docker/envs/.env.staging  # STAGING ENV

  celery_beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production  # PRODUCTION TARGET
    env_file:
      - docker/envs/.env.staging  # STAGING ENV

  caddy:
    env_file:
      - docker/envs/.env.staging  # STAGING ENV
    volumes:
      - ./docker/caddy/Caddyfile.staging:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
