version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production  # PRODUCTION TARGET
    env_file:
      - docker/envs/.env.prod  # PRODUCTION ENV

  db:
    env_file:
      - docker/envs/.env.prod  # PRODUCTION ENV

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production  # PRODUCTION TARGET
    env_file:
      - docker/envs/.env.prod  # PRODUCTION ENV

  celery_beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production  # PRODUCTION TARGET
    env_file:
      - docker/envs/.env.prod  # PRODUCTION ENV

  caddy:
    env_file:
      - docker/envs/.env.prod  # PRODUCTION ENV
    volumes:
      - ./docker/caddy/Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
